// <auto-generated />
using KendoDemo.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace KendoDemo.API.Migrations
{
    [DbContext(typeof(KendoContext))]
    [Migration("20190116192536_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("KendoDemo.API.Models.Kendo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("About");

                    b.Property<string>("Address");

                    b.Property<int>("Age");

                    b.Property<string>("Balance");

                    b.Property<string>("Company");

                    b.Property<string>("Email");

                    b.Property<string>("EyeColor");

                    b.Property<string>("FavoriteFurit");

                    b.Property<string>("FullName");

                    b.Property<string>("Greeting");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Phone");

                    b.Property<string>("Picture");

                    b.Property<string>("Registered");

                    b.HasKey("Id");

                    b.ToTable("Kendos");
                });
#pragma warning restore 612, 618
        }
    }
}
